# Notes
# - cannot run on Windows, as we use shell scripts
# - Most jobs require a Helidon priming build to execute

name: "Validate examples"

on: [pull_request, workflow_call]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'
  HELIDON_PIPELINES: 'true'
  MAVEN_HTTP_ARGS: '-Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3'
  HELIDON_EXAMPLES_REPOSITORY: 'helidon-io/helidon.git'
  HELIDON_EXAMPLES_BUILD_BRANCH: 'helidon-3.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  primebuild:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          repository: ${{ env.HELIDON_EXAMPLES_REPOSITORY }}
          ref: ${{ env.HELIDON_EXAMPLES_BUILD_BRANCH }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Helidon Priming build
        run: |
          mkdir -p ~/.m2/repository/io/helidon/
          echo "empty file" > ~/.m2/repository/io/helidon/empty.txt
          etc/scripts/primebuild.sh
      - name: Upload Maven Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: io-helidon-maven-artifacts
          path: ~/.m2/repository/io/helidon
          retention-days: 1
  buildexamples:
    needs: primebuild
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Download Maven Artifacts
        uses: actions/download-artifact@v3
        with:
          name: io-helidon-maven-artifacts
          path: ~/.m2/repository/io/helidon
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Maven build
        run: etc/scripts/build.sh
